class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirrorcl'
        self.UnzipMirrorCommand = 'unzipmirrorcl'
        self.TarMirrorCommand = 'tarmirrorcl'
        self.CancelMirror = 'cancelcl'
        self.CancelAllCommand = 'cancelallcl'
        self.ListCommand = 'listcl'
        self.StatusCommand = 'statuscl'
        self.AuthorizedUsersCommand = 'userscl'
        self.AuthorizeCommand = 'authorizecl'
        self.UnAuthorizeCommand = 'unauthorizecl'
        self.AddSudoCommand = 'addsudocl'
        self.RmSudoCommand = 'rmsudocl'
        self.PingCommand = 'pingcl'
        self.RestartCommand = 'restartcl'
        self.StatsCommand = 'statscl'
        self.HelpCommand = 'helpcl'
        self.LogCommand = 'logcl'
        self.SpeedCommand = 'speedtestcl'
        self.CloneCommand = 'clonecl'
        self.CountCommand = 'countcl'
        self.WatchCommand = 'watchcl'
        self.TarWatchCommand = 'tarwatchcl'
        self.DeleteCommand = 'delcl'
        self.UsageCommand = 'usagecl'
        self.MediaInfoCommand = 'mediainfocl'
        self.ConfigMenuCommand = 'configcl'
        self.ShellCommand = 'shellcl'
        self.UpdateCommand = 'updatecl'

BotCommands = _BotCommands()
