class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirrorml'
        self.UnzipMirrorCommand = 'unzipmirrorml'
        self.TarMirrorCommand = 'tarmirrorml'
        self.CancelMirror = 'cancelml'
        self.CancelAllCommand = 'cancelallml'
        self.ListCommand = 'listml'
        self.StatusCommand = 'statusml'
        self.AuthorizedUsersCommand = 'usersml'
        self.AuthorizeCommand = 'authorizeml'
        self.UnAuthorizeCommand = 'unauthorizeml'
        self.AddSudoCommand = 'addsudoml'
        self.RmSudoCommand = 'rmsudoml'
        self.PingCommand = 'pingml'
        self.RestartCommand = 'restartml'
        self.StatsCommand = 'statsml'
        self.HelpCommand = 'helpml'
        self.LogCommand = 'logml'
        self.SpeedCommand = 'speedtestml'
        self.CloneCommand = 'cloneml'
        self.CountCommand = 'countml'
        self.WatchCommand = 'watchml'
        self.TarWatchCommand = 'tarwatchml'
        self.DeleteCommand = 'delml'
        self.UsageCommand = 'usageml'

BotCommands = _BotCommands()
